// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD40eOyDHVYNa8UikWK596xGhnQ_7meZ8',
    appId: '1:399384419181:web:c59dda48de8cbb99b1d864',
    messagingSenderId: '399384419181',
    projectId: 'medico-c769f',
    authDomain: 'medico-c769f.firebaseapp.com',
    storageBucket: 'medico-c769f.firebasestorage.app',
    measurementId: 'G-YW67Z8SWX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhV7hhFeW37WT_j3lp3G2KzhQ0Xbnuybo',
    appId: '1:399384419181:android:5d06f17318a509ceb1d864',
    messagingSenderId: '399384419181',
    projectId: 'medico-c769f',
    storageBucket: 'medico-c769f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdFEdmZvR0P48BE3T6B4IZiOSozrpbyX0',
    appId: '1:399384419181:ios:e66ddf08bcf2605eb1d864',
    messagingSenderId: '399384419181',
    projectId: 'medico-c769f',
    storageBucket: 'medico-c769f.firebasestorage.app',
    iosBundleId: 'com.medico.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdFEdmZvR0P48BE3T6B4IZiOSozrpbyX0',
    appId: '1:399384419181:ios:003428ddc43b2665b1d864',
    messagingSenderId: '399384419181',
    projectId: 'medico-c769f',
    storageBucket: 'medico-c769f.firebasestorage.app',
    iosBundleId: 'com.example.medico',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD40eOyDHVYNa8UikWK596xGhnQ_7meZ8',
    appId: '1:399384419181:web:3c8a5513bbdebfa3b1d864',
    messagingSenderId: '399384419181',
    projectId: 'medico-c769f',
    authDomain: 'medico-c769f.firebaseapp.com',
    storageBucket: 'medico-c769f.firebasestorage.app',
    measurementId: 'G-89185YR22F',
  );
}
